//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizSystemApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TakeExam
    {
        public int id { get; set; }
        public int student_id { get; set; }
        public int exam_id { get; set; }
        public System.DateTime date { get; set; }
        public int amountCorrectAnswer { get; set; }
        public int amountWrongAnswer { get; set; }
    
        public virtual Exam Exam { get; set; }
        public virtual Student Student { get; set; }
    }
}
