//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizSystemApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variant
    {
        public int id { get; set; }
        public string variantType { get; set; }
        public string variantText { get; set; }
        public int questionId { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
